### ISSUE TITLE
Hardcode resolver and python toolkit for DNS

### ISSUE THREAD

**Issue by ongolaboy** [Sanix-Darker/TWITTER-CHALLENGE-MX-SERVER#1]
https://github.com/Sanix-Darker/TWITTER-CHALLENGE-MX-SERVER/blob/78a651e687ec669729d88f5d23fc87d319944841/main.py#L30

Bonjour, je te conseille de ne pas coder en dur un résolveur comme celui de google que tu as choisis.

De plus, si tu veux faire des résolutions DNS et de surcroît en python, c'est mieux de rechercher des librairies existantes. Ex: [dnspython](https://github.com/rthalley/dnspython)

**Comment by Sanix-Darker** [comment]
Ok, c'est compris.
